version: '3.9'

services:
  nats:
    image: nats:latest
    ports:
      - "4222:4222"
      - "8222:8222"
    command: ["-js", "-m", "8222"]  # فعال کردن JetStream و dashboard
    restart: always

  publisher:
    build: ./publisher
    depends_on:
      - nats

  worker:
    build: ./worker
    depends_on:
      - nats
